name: Package Pre Updater For Avia.js

on:
  workflow_dispatch:

env:
  PACKAGES: '@inertiajs/react @types/react'
  PACKAGE_PATH: 'package.json'

jobs:
  update-avia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get latest versions and check outdated packages
        id: check-outdated
        run: |
          outdated=""
          tmp_file=${PACKAGE_PATH}.tmp
          cp $PACKAGE_PATH "$tmp_file"
          for pkg in $PACKAGES; do
            latest=$(npm view $pkg version)
            current=$(jq -r ".dependencies[\"$pkg\"]" "$PACKAGE_PATH")
            if [ -n "$current" ] && [ "$current" != "$latest" ]; then
              echo "$pkg is outdated: $current --> $latest"
              jq --arg pkg "$pkg" --arg version "$latest" '
              if .dependencies[$pkg] then .dependencies[$pkg] = $version else . end
              ' "$tmp_file" > "$tmp_file.new" && mv "$tmp_file.new" "$tmp_file"
              outdated="true"
            fi
          done
          mv "$tmp_file" "$PACKAGE_PATH"
          [ -f "$tmp_file.new" ] && rm "$tmp_file.new"
          echo "outdated=$outdated" >> $GITHUB_OUTPUT

      - name: Create PR if outdated
        if: steps.check-outdated.outputs.outdated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'chore/update-avia'
          commit-message: 'chore: Update Avia packages to latest versions'
          title: 'chore: Update avia  package'
          body: |
            This PR updates the following packages to their latest versions: ${{ env.PACKAGES }}
